name: Deploy MkDocs

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build site with MkDocs
      run: mkdocs build --verbose

    - name: Upload built site as artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: public/

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4